config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'docs#new'
  resources :docs, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  require 'smarter_csv'
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  def new
  end

  def create
    # begin
      uploaded = params[:file]
      File.open("./tmp/csv_doc.csv", 'w') do |file|
        file.write(uploaded.read)
      end

      lines = SmarterCSV.process('./tmp/csv_doc.csv')
      @new_hash = lines

      lines.each_with_index do |l1, index1|
        @new_hash.each_with_index do |l2, index2|
          if index1 != index2
            if (lines[index1][:nombre].to_s == @new_hash[index2][:nombre].to_s) && (lines[index1][:correo_electronico].to_s == @new_hash[index2][:correo_electronico].to_s) && (lines[index1][:telefono].to_s == @new_hash[index2][:telefono].to_s)
              @new_hash.delete_at(index2)
            end

            if is_valid_email?(@new_hash[index2][:correo_electronico]).nil?
              @new_hash.delete_at(index2)
            end

            if (lines[index1][:nombre].to_s == @new_hash[index2][:nombre].to_s) || (lines[index1][:correo_electronico].to_s == @new_hash[index2][:correo_electronico].to_s) || (lines[index1][:telefono].to_s == @new_hash[index2][:telefono].to_s)
              @new_hash[index1][:flag] = 0
              @new_hash[index2][:flag] = 0
            end
          end
        end
      end
    # rescue
    #   redirect_to root_path
    # end
  end

  private
    def is_valid_email? email
      email =~ VALID_EMAIL_REGEX
    end

    def deep_copy(o)
      Marshal.load(Marshal.dump(o))
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/docs/create.html.erb
<h2 class="text-center">Datos procesados</h2>
<div class="alert alert-primary" role="alert">
    Todos los registros duplicados fueron eliminados excepto uno.
    Los registros que tenian un correo electronico invalido fueron eliminados.
    Los registros que tienen algun campo duplicado se marcaron en amarillo
  </div>

<table class="table table-bordered">
  <thead><tr><th scope="col"></th><th scope="col">Nombre</th><th scope="col">Correo Electronico</th scope="col"><th scope="col">Telefono</th></tr></thead>
  <tbody>
    <% @new_hash.each_with_index do |h, i| %>
      <% if !h[:flag].nil? && h[:flag] == 0 %>
        <tr class="table-warning"><th scope="row"><%= i + 1 %></th><td><%= h[:nombre] %></td><td><%= h[:correo_electronico] %></td><td><%= h[:telefono] %></td></tr>
      <% else %>
        <tr><th scope="row"><%= i + 1 %></th><td><%= h[:nombre] %></td><td><%= h[:correo_electronico] %></td><td><%= h[:telefono] %></td></tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/docs/new.html.erb
<div class="text-center">
  <h2>Archivo CSV</h2>
  <div class="alert alert-primary" role="alert">
    Seleccionar y subir un archivo CSV con los campos de nombre, correo_electronico, telefono.
  </div>
</div>
<div class="text-center">
  <%= form_tag(docs_path(), { :multipart => true }) do %>
    <%= label_tag(:file, "Subir archivo CSV:") %>
    <%= file_field_tag "file" %>
    <%= submit_tag("Subir") %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Csv Doc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>